### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by SOUMEE2000** [soumitri2001/Flower-Classification-pytorch#1]
Hello.
I am trying to learn from your code and I had the following questions. 
Could you say how long it took to complete your training, with one set of parameters and how they varied with other sets?
Also could you mention in your code which part is the feature extraction?

Thanking you in advance.

**Comment by soumitri2001** [comment]
Hello,

For the first question, the training took roughly around 15-20 minutes on google colab GPU. Downloading the pre-trained model hardly took a couple of minutes on the same.

For the second question, the eval_model_extract_features(...) does the feature extraction along with evaluating, values get stored in the "features" list. 

Hope that helps :)

**Comment by SOUMEE2000** [comment]
Thank you that helps a lot.
